### ISSUE TITLE
Show connection details

### ISSUE THREAD

**Issue by ajayyy** [uorocketry/RocketGroundStation2020#18]
Data per second - calculated
Time of last packet - calculated
Packet loss - calculated
Other RSSI data - from RSSI packets

In sidebar

**Comment by sebastiengrd** [comment]
DOD:

- [ ] Create another class - dataPrecessor
- [ ] This class takes the data and parse it and logs it
- [ ] The UI uses dataProcessor to create the graphs/update the tables
- [ ] There is only one dataProcessor for all input
- [ ] There is one file for each input
- [ ] All the telemetry data will be saved in dataHandeler - even the RSSI stuff
- [ ] The simulation should work with this new dataProcessor

**Comment by ajayyy** [comment]
RSSI parsing ideas:

For pre-protobuf:
`realDaRSSI:saljadskl\ntamorerealdata\n`

cut off the first part by searching for RSSI, potentially store for later. Add to the next packet. Since it always is looking for packets up to the next newline character, it should be fine.

For protobuf:
Read first bit and treat that as a anunber of bits of the packet. After recieving each byte, check if the last bytes are equal to "RSSI:", if so, keep going to the newline character instead and ignore the first bytes.
Advantage: this will work with protobuf data that has rssi data in the middle
